### ISSUE TITLE
did something change about how the files are written/read?

### ISSUE THREAD

**Issue by chauey** [Nanciee/cypress-autorecord#16]
how to migrate if so, thx

UPDATE: i do see some commits in past 8 days around this...

**Comment by Nanciee** [comment]
You no longer need to pass in the `__filename` into `autorecord()`. This shouldn't be a breaking change as it is now extracting the same information about the filename through the built in `Cypress.spec.name`. This is the PR with the changes: https://github.com/Nanciee/cypress-autorecord/pull/14

If this isnt working for you, please send over the issue you are seeing! 😊

**Comment by chauey** [comment]
May be related to using Nx. It used to use path like:
'apps/project-name/cypress/mocks/file-name.json'.

Now it tries to use:
'dist/out-tsc/apps/project-name/src/mocks/folder-name\file-name.json'

1. different root, 2. has child folder name, and 3. the last slash is a back-slash (using Windows)

It says contains invalid WIN32 path characters, I think related to the escaping in 3, which is part of the "fileName" value perhaps.

Do I need to remove passing in  the __filename. Will try that, etc. thx.

UPDATE: error message is 
>"absolute-path-to-project-folder + '/' + absolute-path-to-output-folder-and-mocks-sub-folder contains invalid WIN32 path characters."

![image](https://user-images.githubusercontent.com/5130533/62093061-6cd29500-b23d-11e9-8b50-b007c041d575.png)

**Comment by chauey** [comment]
Updating to latest angular Nx workspace (with relative paths in cypress.json) seems to work better, but still testing/investigating...

**Comment by Nanciee** [comment]
Going to close this for now! Please reopen if you see any issues

**Comment by hkarambizi** [comment]
@Nanciee 
I am having an issue where after I do initial config and test to see if it works, it appears that it is not writing to the appropriate directory but rather it is writing to:

**${rootDirectory}/${AbsoluteFilePath}**

I tried to debug with console.log to see what is happening, but when I replicate the code, it appears to log the correct filepath.

Here is my config in **plugins/index.js**:
```
const fs = require("fs");
const autoRecord = require("cypress-autorecord/plugin");

module.exports = (on, config) => {
  autoRecord(on, config, fs);
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
};
```

Here is the code in my spec file:
```
const autoRecord = require("cypress-autorecord");
const path = require("path");
const baseUrl = Cypress.env("url") + "/app";

describe("Gather Lead Testing", function() {
  autoRecord();

  it("[r] should create a new lead", function() {
    cy.visit(baseUrl);

    // trying to debug the source code
    const fixturesFolder = Cypress.config("fixturesFolder").replace(/\\/g, "/");
    const mocksFolder = path.join(fixturesFolder, "../mocks");
    const fileName = path.basename(
      Cypress.spec.name,
      path.extname(Cypress.spec.name)
    );
    console.log("This is the mocksFolder: ", mocksFolder);
    console.log("This is the fileName: ", fileName);
  });
});
```

Here is the output of when I console log the **mocksFolder** and **fileName**:

<img width="1135" alt="Debugging File Path with Console Log" src="https://user-images.githubusercontent.com/22929885/66530524-1f449500-ead6-11e9-9b5b-5eb8d5449924.png">


Here are the screenshots after I run the tests:

<img width="1061" alt="WriteFile After Test Run" src="https://user-images.githubusercontent.com/22929885/66530531-2370b280-ead6-11e9-8936-08694e0438d4.png">

**Comment by hkarambizi** [comment]
Welp. It looks like it had an issue with my cypress version. I was running 3.2.0

`
npm install --save-dev cypress@3.4.1
`

did the trick!
