### ISSUE TITLE
support graphql endpoint mocking

### ISSUE THREAD

**Issue by scottbarrow** [Nanciee/cypress-autorecord#25]
I see that route endpoint blacklisting is possible using the `blacklistRoutes` config option, however when making requests to a graphql endpoint all routes are `hostname:port/graphql`. 
It would be great if autorecord supported blacklisting of graphql's `operationName` found in the request body, which determines the graphql query/endpoint being requested. 

Is it possible to achieve this some other way?

**Comment by bautistaaa** [comment]
we currently append operationName to the url itself in the context of cypress. not the greatest solution but it doesn't require any code changes in this repo

**Comment by scottbarrow** [comment]
Thanks, I actually got VCR working for my use(recording external API calls) and hook into it using cypress-on-rails with an app command. Which is better as I didn't really want to mock out the whole graphql call
