### ISSUE TITLE
Fetch() defaults to 'get' as method (instead of 'GET')

### ISSUE THREAD

**Issue by marienvo** [Nanciee/cypress-autorecord#40]
In our project the browsers `fetch()` function seems to default the request method to `get` (instead of uppercase `GET`); and since the `supportedMethods` array is all uppercase, this breaks our tests when running with the recorded mocks.

Recording is fine though, but the JSON is incompatible (or lowercase `get` needs to be added to supportedMethods):

![Screenshot from 2021-01-06 11-32-01](https://user-images.githubusercontent.com/8506573/103758757-eb2a8d80-5012-11eb-8385-2c6e254ac893.png)

This seems to 'fix' the issue: `const supportedMethods = ['get', 'GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD'];`

**Comment by Nanciee** [comment]
Thanks for raising this! I'll add in a quick fix this for this. Was this only limited to 'get' or would other request types need to be added as well?

**Comment by marienvo** [comment]
Thanks! Only the lowercase 'get' gave issues for us, no other request types as far as we've experienced.
