### ISSUE TITLE
`cy.clock` makes my spec hang

### ISSUE THREAD

**Issue by ha404** [Nanciee/cypress-autorecord#41]
For some reason this line that establishes `cy.clock` makes my spec hang. 

I'll attempt to `cy.visit` a route and never resolve. Network requests seem to never occur, it's like I'm frozen in time.

https://github.com/Nanciee/cypress-autorecord/blob/3662aee3faaeb4bddb381fd616d6aa6a87701dde/index.js#L182-L186

After commenting all instances of `cy.clock` everything works fine. Any ideas?

Thanks!

**Comment by Nanciee** [comment]
Let me take a look into this

**Comment by ha404** [comment]
@Nanciee @RobertCorey I found a way to get around this for the time being by adding this to you `beforeEach` in each of your specs:

From https://docs.cypress.io/api/commands/clock#Restore-clock:
```javascript
beforeEach(() => {
  cy.clock().invoke('restore')
})
```

**Comment by ha404** [comment]
I've made a PR to restore it within the plugin: https://github.com/Nanciee/cypress-autorecord/pull/46/files?w=1

**Comment by ha404** [comment]
🎉 Resolved: https://github.com/Nanciee/cypress-autorecord/pull/46/files?w=1
