### ISSUE TITLE
Usage with cypress-cucumber-preprocessor?

### ISSUE THREAD

**Issue by mrkerr** [Nanciee/cypress-autorecord#53]
I've got cypress cucumber tests that I'm trying to record http interactions with. Recording with autorecord works and successfully creates the mocks and fixtures, however, when trying to re-run the tests with the recorded json I'm getting an error saying
```  
> Unexpected token ':'
```

I can't seem to figure out where this error is originating from as the stack trace is empty.
<img width="522" alt="Screen Shot 2021-06-11 at 12 52 35 PM" src="https://user-images.githubusercontent.com/26953673/121729366-0151e380-cab4-11eb-9eff-6264f2a523c3.png">
<img width="522" alt="Screen Shot 2021-06-11 at 12 52 47 PM" src="https://user-images.githubusercontent.com/26953673/121729375-02831080-cab4-11eb-88dd-9034351d593a.png">

**Comment by DaveClissold** [comment]
@mrkerr can I ask how you got autorecord running with cucumber-preprocessor?  I'm not getting any errors but it's not recording, just wondering if you had to do anything in particular to get it working?

**Comment by mrkerr** [comment]
@DaveClissold
Hey there! I actually got everything working with the recorded http interactions. I just followed the readme to set it up and then called `autoRecord()` at the top of all my step files. I think the only weird thing is that I had to specify an intercept pattern.
