### ISSUE TITLE
FixtureId is not working with req.reply 

### ISSUE THREAD

**Issue by ErichSA** [Nanciee/cypress-autorecord#54]
Cypress is not returning the fixture
index.js line 169: req.reply(response.status, newResponse, response.headers);
It's returning the fixture folder instead.
![image](https://user-images.githubusercontent.com/28894552/123011155-e291fd80-d38d-11eb-83eb-b73d4f7603c1.png)
Changing it to:
```
let newResponse = response.response;
            if (response.fixtureId) {
              newResponse = {
                statusCode: response.status,
                fixture: `${fixturesFolderSubDirectory}/${response.fixtureId}.json`
              };
            }
req.reply(newResponse, response.headers);
```
Everything works.

**Comment by ErichSA** [comment]
Can I open a PR?
This is the cypress documentation:
![image](https://user-images.githubusercontent.com/28894552/123011446-66e48080-d38e-11eb-94cc-66900950a567.png)
https://docs.cypress.io/api/commands/intercept#Request-Response-Modification-with-routeHandler

**Comment by MasterATM** [comment]
Hello,
I got the same problem as initially described despite using the latest 3.1.2 version.
The signature for res.send is different if we want to reply with either the direct response or a fixture.

If if modify the code to this, then it works:
```
            req.reply((res) => {
              const newResponse = sortedRoutes[method][url][index];
              if (newResponse.fixtureId) {
                res.send(
                  {
                        fixture: `${fixturesFolderSubDirectory}/${newResponse.fixtureId}.json`,
                        headers: newResponse.headers,
                        statusCode: newResponse.status
                  }
                );  
              } else {
                res.send(
                  newResponse.status,
                  newResponse.response,
                  newResponse.headers,
                );  
              }
```
Thanks.
