### ISSUE TITLE
interceptPattern doesn't work with regex

### ISSUE THREAD

**Issue by ERuseckas** [Nanciee/cypress-autorecord#56]
Passing valid regex:
1. `interceptPattern: new RegExp(REGEX_STRING)`
2. `interceptPattern: /REGEX_STRING/`
results in interceptPattern becoming as `{}`

If I convert valid regexp into string, then it's value is used as glob, not regex.

I see here 2 possible options:
1. parse `interceptPattern` value to figure out is it regex or not
2. change plugin, so that user could pass plugin config without using Cypress config

**Comment by Nanciee** [comment]
resolved in v3.1.2!
